### ISSUE TITLE
Proposals fail to load - TypeError: Cannot read property 'proposal' of undefined

### ISSUE THREAD

**Issue by Zil-B** [harmony-one/snapshot-spaces#14]
### Expected behavior
Proposals on [https://gov.harmony.one/#/](https://gov.harmony.one/#/ ) should load successfully and allow users to view all proposals, and vote on active ones.

### Actual behavior
The majority of proposals fail to load.

The Harmony Mainnet, Harmony Testnet, Validator Dao Mainnet, and Validator Dao Testnet spaces load the proposals with no issues.

All others get stuck trying to load the proposals (for active, pending, and closed).

![moonityproposal](https://user-images.githubusercontent.com/84344709/125207439-45d3c900-e284-11eb-8e39-90275e6d71fe.png)
![lma proposal](https://user-images.githubusercontent.com/84344709/125207440-45d3c900-e284-11eb-8eff-35211f0b3cf9.png)
![xyaproposal](https://user-images.githubusercontent.com/84344709/125207441-466c5f80-e284-11eb-81bb-76c7c87dd63f.png)
![viperproposal](https://user-images.githubusercontent.com/84344709/125207443-466c5f80-e284-11eb-81ea-5672b478f201.png)

This has been a persistent bug for several months. Sometimes a proposal will load, but the vast majority of the time it gets stuck loading the proposals. Many users have reported in community TG channels that they are having this same issue.

The console logs "TypeError: Cannot read property 'proposal' of undefined".

![consolelog](https://user-images.githubusercontent.com/84344709/125207438-453b3280-e284-11eb-8559-ec8b53055f45.png)

### Steps to reproduce the behavior

1. Visit a space other than Harmony Mainnet, Harmony Testnet, Validator Dao Mainnet, and Validator Dao Testnet on [https://gov.harmony.one/#/](https://gov.harmony.one/#/ )
2. Open any proposal (active, closed, or pending)

**Comment by jhd2best** [comment]
thanks for feedback. get some information after detect the error:
sometimes the IPFS request will return 503 when load the proposal(see the image below). will try to fixed it. let it more stable then.
![image](https://user-images.githubusercontent.com/8352895/125303886-b996d400-e35f-11eb-8a89-104567cf0af5.png)

**Comment by jhd2best** [comment]
hey @Zil-B . we have optimized the RPC interface of mainnet government. can you help me check whether it is sitll always fail to load. thanks

**Comment by Zil-B** [comment]
@jhd2best Working great on my end, and users are reporting the same. Proposals all load within seconds. Good to close?
Thanks

**Comment by Zil-B** [comment]
Closing - issue seems to be resolved
