### ISSUE TITLE
Not seeing Arb/Troll/Bard spaces

### ISSUE THREAD

**Issue by defiproject** [harmony-one/snapshot-spaces#21]
### Expected behavior
1- Navigate to https://gov.harmony.one/#/
2- See Arb, Troll, Bard spaces
3- Total spaces displayed should be 21

### Actual behavior
1- Navigate to https://gov.harmony.one/#/
2- Only see 18 spaces and not 21 spaces
<img width="540" alt="Screen Shot 2021-08-17 at 1 46 05 PM" src="https://user-images.githubusercontent.com/79382343/129790552-2f81a7a4-e8f6-4fe9-850c-aaa1e84c61f9.png">

### Steps to reproduce the behavior
1-Navigate to https://gov.harmony.one/#/

4 days ago their was a PR merged with the following spaces added https://github.com/harmony-one/snapshot-spaces/pull/20

was the commit done wrong?  How come I do not see the 3 additional spaces on the governance website?

**Comment by jhd2best** [comment]
already added
